# Site settings
title: Jacqlene Develops
header-img: img/home-bg.png
email: jsifre01@gmail.com
copyright_name: jss530
description: > # this means to ignore newlines until "baseurl:"
  My journey to becoming a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jss530
learn_profile: jss530
email_username: jsifre01@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
